import ProfilePics from "../../assests/admin.png";

const MerchantsData = [
  {
    id: 11,
    pictureAddress: ProfilePics,
    firstname: "John",
    lastname: "Tutor1",
    username: "@thealisoneyo",
    email: "merchant1@example.com",
    isSuspended: "true",
  },
  {
    id: 12,
    pictureAddress: ProfilePics,
    firstname: "John",
    lastname: "Tutor2",
    username: "@thealisoneyo",
    email: "merchant2@example.com",
    isSuspended: "true",
  },
  {
    id: 13,
    pictureAddress: ProfilePics,
    firstname: "John",
    lastname: "Tutor3",
    username: "@thealisoneyo",
    email: "merchant3@example.com",
    isSuspended: "Deactivated",
  },
  {
    id: 14,
    pictureAddress: ProfilePics,
    firstname: "John",
    lastname: "Tutor4",
    username: "@thealisoneyo",
    email: "merchant4@example.com",
    isSuspended: "true",
  },
  {
    id: 15,
    pictureAddress: ProfilePics,
    firstname: "John",
    lastname: "Tutor5",
    username: "@thealisoneyo",
    email: "merchant5@example.com",
    isSuspended: "Deactivated",
  },
  {
    id: 16,
    pictureAddress: ProfilePics,
    firstname: "John",
    lastname: "Tutor6",
    username: "@thealisoneyo",
    email: "merchant6@example.com",
    isSuspended: "Deactivated",
  },
  {
    id: 17,
    pictureAddress: ProfilePics,
    firstname: "John",
    lastname: "Tutor7",
    username: "@thealisoneyo",
    email: "merchant7@example.com",
    isSuspended: "true",
  },
  {
    id: 18,
    pictureAddress: ProfilePics,
    firstname: "John",
    lastname: "Tutor8",
    username: "@thealisoneyo",
    email: "merchant8@example.com",
    isSuspended: "Deactivated",
  },
  {
    id: 19,
    pictureAddress: ProfilePics,
    firstname: "John",
    lastname: "Tutor9",
    username: "@thealisoneyo",
    email: "merchant9@example.com",
    isSuspended: "true",
  },
  {
    id: 20,
    pictureAddress: ProfilePics,
    firstname: "John",
    lastname: "Tutor10",
    username: "@thealisoneyo",
    email: "merchant10@example.com",
    isSuspended: "true",
  },
];

export default MerchantsData;
