import ProfilePics from "../../assests/merchants.jpeg";

const UserData = [
  {
    id: 1,
    pictureAddress: ProfilePics,
    firstname: "Gabriella",
    lastname: "McPherson",
    username: "@thealisoneyo",
    email: "merchant1@example.com",
    isSuspended: "true",
  },
  {
    id: 2,
    pictureAddress: ProfilePics,
    firstname: "Gabriella",
    lastname: "McPherson",
    username: "@thealisoneyo",
    email: "merchant2@example.com",
    isSuspended: "true",
  },
  {
    id: 3,
    pictureAddress: ProfilePics,
    firstname: "Gabriella",
    lastname: "McPherson",
    username: "@thealisoneyo",
    email: "merchant3@example.com",
    isSuspended: "Deactivated",
  },
  {
    id: 4,
    pictureAddress: ProfilePics,
    firstname: "Gabriella",
    lastname: "McPherson",
    username: "@thealisoneyo",
    email: "merchant4@example.com",
    isSuspended: "true",
  },
  {
    id: 5,
    pictureAddress: ProfilePics,
    firstname: "Gabriella",
    lastname: "McPherson",
    username: "@thealisoneyo",
    email: "merchant5@example.com",
    isSuspended: "Deactivated",
  },
  {
    id: 6,
    pictureAddress: ProfilePics,
    firstname: "Gabriella",
    lastname: "McPherson",
    username: "@thealisoneyo",
    email: "merchant6@example.com",
    isSuspended: "Deactivated",
  },
  {
    id: 7,
    pictureAddress: ProfilePics,
    firstname: "Gabriella",
    lastname: "McPherson",
    username: "@thealisoneyo",
    email: "merchant7@example.com",
    isSuspended: "true",
  },
  {
    id: 8,
    pictureAddress: ProfilePics,
    firstname: "Gabriella",
    lastname: "McPherson",
    username: "@thealisoneyo",
    email: "merchant8@example.com",
    isSuspended: "Deactivated",
  },
  {
    id: 9,
    pictureAddress: ProfilePics,
    firstname: "Gabriella",
    lastname: "McPherson",
    username: "@thealisoneyo",
    email: "merchant9@example.com",
    isSuspended: "true",
  },
  {
    id: 10,
    pictureAddress: ProfilePics,
    firstname: "Gabriella",
    lastname: "McPherson",
    username: "@thealisoneyo",
    email: "merchant10@example.com",
    isSuspended: "true",
  },
];

export default UserData;
